# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias_name',
            field=models.CharField(default='', max_length=50, verbose_name='\u522b\u540d'),
        ),
    ]
