# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ss', '0003_auto_20180604_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='oneline',
            field=models.IntegerField(default=0),
        ),
    ]
