# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ss', '0004_host_oneline'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmessage',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='create time'),
        ),
        migrations.AddField(
            model_name='host',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='create time'),
        ),
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='create time'),
        ),
        migrations.AddField(
            model_name='vplog',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='create time'),
        ),
        migrations.AlterField(
            model_name='host',
            name='oneline',
            field=models.IntegerField(default=0, verbose_name='\u5728\u7ebf\u4eba\u6570'),
        ),
    ]
